---
# Base container images aren't used for creating stand-alone
# containers. Rather, they are images that will be used by
# other projects to build their final image. The advantage
# of having a base image pipeline is that it can significantly
# speed up the pipelines of other projects since most of the
# dependencies will have already been baked into the base image.

# Which version of the base-container-image pipeline
# does this config file use?
pipeline_version: base-container-image/v1

# The name of the base container image. DO NOT add a
# ':<version>' here since the pipeline will automatically
# add that on successful build. Instead, declare the image's
# version in the VERSION file. You can use whatever versioning
# scheme works best for you but SemVer 2.0.0 is recommended.
# The pipeline will append extra build information to that
# to form a globally unique version (AKA build ID).
image_name: sample-base-container-image

# Where will the image be pushed as it gets built and promoted
# in its pipeline? Note that the underlying CI/CD cluster must
# already have access to these registries.
image_registries:
  dev:  docker.io/relaxdiegodev
  qa:   docker.io/relaxdiegoqa
  prod: docker.io/relaxdiego

# Which channel in the underlying chat provider will the pipeline
# push notifications? Note that the underlying CI/CD cluster must
# already be configured to access the chat provider and must also
# have access to this channel.
notify_channel: sample-base-container-builds
